DROP SEQUENCE if EXISTS SQ_CUSTOMER;

CREATE SEQUENCE SQ_CUSTOMER START WITH 1 INCREMENT BY 1;

DROP TABLE IF EXISTS TBL_CUSTOMER;

CREATE TABLE TBL_CUSTOMER(
ID BIGINT NOT NULL,
UUID VARCHAR(36) NOT NULL,
CPF VARCHAR(100) NOT NULL,
CUSTOMER_NAME VARCHAR(100) NOT NULL,
CUSTOMER_AGE VARCHAR(3) NOT NULL,
INC_DATE TIMESTAMP NOT NULL,
MODF_DATE TIMESTAMP,
PRIMARY KEY(ID)
);